---
title: "Time-series of RADAR backscatter using GEE and R"
author: "Francesco Pirotti [&lt;francesco.pirotti@unipd.it&gt;](mailto:francesco.pirotti@unipd.it)"
date: "\\#Summer Webinar Series — August 5, 2020"
output:
  revealjs::revealjs_presentation:
    theme: night
    #transition: none
    self_contained: false
    css: slides.css
  html_document:
    css: slides_presenter.css
  beamer_presentation:
    toc: false
    incremental: false
---

## Agenda

- Continuation from webinar2 where Google Earth Engine (GEE) was used to extract time series per each polygon of areas damaged by VAIA 
- Import extracted data in R CRAN
- Plot time series data and applying a Z-score filter over past N values to detect changes

## Before we begin

- For this Webinar we use  RStudio - if you want to follow along, make sure you have an account with GEE and have installed R + RStudio in your PC - and you have downloaded some polygons of data - I suggest to start with not more than 10-20 polygons for the excercises.
 
**Will it be recorded?** 

Slides and exercises will also be available on GitHub:    

[https://github.com/fpirotti/webinar_series_R_GEE](https://github.com/fpirotti/webinar_series_R_GEE)


## What we will touch on

### Part 1

- Starting a repository in [GITHUB](https://github.com/) to share/sync/backup your data   
- Starting a project in R - RStudio linking to GITHUB
- Uploading to R data in GEOJson format that was exported from GEE


### Part 2

- Plotting in R
- Filtering in R


 

## R CRAN

More coming...

&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  