---
title: "Sentinel-1 backscatter for forest analysis: can we push the limit?"
author:
- affiliation: CIRGEO Interdepartmental Research Center of Research of Geomatics
  corresponding: francesco.pirotti@unipd.it
  email: francesco.pirotti@unipd.it
  footnote: 1
  name: Francesco Pirotti
  orcid: 0000-0002-4796-6406
- affiliation: TESAF Department
  email: francesco.pirotti@unipd.it
  footnote: 2
  name: Francesco Pirotti
  orcid: 0000-0002-4796-6406
date: "`r Sys.Date()`"
output:
  pdf_document: rticles::elsevier_article
  html_document:
    df_print: paged
    self_contained: false
  word_document: default
csl: elsevier-harvard.csl
address:
- address: Agripolis, University of Padova, Legnaro 35020, Italy
  code: CIRGEO Interdepartmental Research Center of Research of Geomatics
- address: University of Padova, Legnaro 35020, Italy
  code: TESAF Department
footnote:
- code: 1
  text: Corresponding Author
- code: 2
  text: Equal contribution
journal: Science of Remote Sensing
bibliography: mybibfile2.bib
link-citations: yes
abstract: |
  This is the abstract.
  It consists of two paragraphs.
---
 


Introduction
===================

In this work the backscatter response of Sentinel-1 C-band signal over forests is analysed to understand to what extent it can be used. Numerous authors have investigated Sentinel-1 for forest analysis, mostly in specific applications. This work wants to partially review past results and provide novel information on how to use backscatter information on forest cover.

Forests are a critical asset of our Earth balance. Forest cover and composition change cyclically over long periods, more drastically after natural or man-induced events such as fires, windthrow and straight tree harvesting. 

Cyclical changes in vegetation is a well-known fact. Most research investigates fisiological changes connected to photosynthesis and climate over seasons. Interestingly even physical position/orientation of leaves and branches can reflect day/night (circadian leaf movements) in birch trees [@Puttonen2016].

The forest cover balance is important to monitor  for well-known reasons [manu citations here]. Optical remote sensing can provide a global watch over land cover in general and forest cover in particular [@Hansen2013; @Margono2014]. 

The known limitation of optical remote sensing is noise from atmospheric elements that cannot be corrected, mainly clouds and smoke. Active remote sensing emits wavelengths that are not significantly influenced by atmospheric conditions and can provide a very helpful complement to optical remote sensing. Radar sensors have been widely used to study vegetation cover, leveraging correlation between backscatter responses and vegetative stage and vegetation type. Unfortunately several other factors influence the return backscatter intensity, the main ones being (i) incidence angle (ii) water content changing the (iii) di-electric constant, (iv) snow/dust cover.


Below the points that are analysed:

- mitigating the effect of irregular terrain ie. mixed incidence angle 
- checking and removing any effect of seasonality 
- define how tree categories influence backscatter
- detecting damaged forests, from
  - pathogens effecting the foliage
  - windstorms


In tropical forests Sentinel 1 and FIRMS has been used [@Reiche2018]

 
Material and methods
===================

The first step consisted the creation of a mask that isolates cells in the study area that were covered more than 95% with tree canopy and that were subject to more than 90% damage from VAIA storm. Furthermore the cell must be part of a damaged site whose area was larger than \( 25000\ m^2 \)  The data consist in Sentinel 1 VV and VH backscatter values only from these masked cells.  ie. that have the following characteristics:

- are completely (>95%) covered by tree canopy - for this the forest cover map from 2000 [@Hansen2013] was used by selecting only cells withe value 100 (100% cover) and removing the ones that recorded loss between the period 2000-2019

- are not covered by snow at time of recording - this was done by removing analysis of the closest Sentinel 2 image before the date of each Sentinel 1 image.  

- are damaged from VAIA's storm - for this the areas with forest loss defined in 2019 from [@Hansen2013] that intersect the areas from [@Forzieri2020] with > 80% damage.   




```{r echo=F}
DiagrammeR::grViz("paper2flow1.gv")
```


 
Theory/calculation
===================

## Sentinel 1

Google Earth Engine (GEE) provides Sentinel 1 in preprocessed GRD products with \( \sigma^0 \) (sigma-naught) of VV and VH polarizations, after processing for removing thermal noise, calibrating radiometry and converting \( \beta^0 \) beta-naught to sigma-naught using a digital elevation model (DEM). The DEM at the latitudes of the analysed study areas used is from the  Shuttle Radar Topography Mission (SRTM) that took place in february 2000 @Farr&Rosen2007. Sigma-naught is provided in dB by transformation the backscatter value  \( Y=10*log_{10}(X) \) . @Small2011.  The GEE product was further transformed to provide gamma-naught (\( \gamma^0 \)) values, thus correcting for the local incidence angle with the SRTM product. This removed the bias between ascending and descenging orbits that was evident from plotting the data.

Incidence angle was further corrected using a frequency-histogram based mehod as described in [@Mladenova2013]. This method is not site-specific or sensor-dependant. Is has also proven to be effective not only for small incidence angles, which is the case here as the area is over mountainous region.


 
## PALSAR-2


Polarization data are stored in GEE as 16-bit digital numbers (DN). As per indication in the GEE website, the DN values can be converted to gamma naught (\( \gamma^0 \))  values in decibel unit (dB) using the following equation: 

\[
\begin{aligned}
 \gamma^0 = 10*log_{10}(DN) - 83.0  
\end{aligned}
\]  

where  \( 83.0 \  dB \) offset and \( \gamma^0 \) is in dB. 

values, thus correcting for the local incidence angle with the SRTM product.  

 
Results
===================



 
Discussion
===================


 
 
Conclusions
===================


 

Acknowledgements
===================


This effort is also part of the [VAIA FRONT project - FRom lessong learned to future Options ](https://www.tesaf.unipd.it/ricerca/progetti-dip-tesaf) . 
     
 
Bibliography styles
===================

There are various bibliography styles available. You can select the
style of your choice in the preamble of this document. These styles are
Elsevier styles based on standard styles like Harvard and Vancouver.
Please use BibTeX to generate your bibliography and include DOIs
whenever available.
 
References {#references .unnumbered}
==========
