---
title: "RADAR Backscatter - can it be used to discriminate damages in forests?"
author:
- affiliation: CIRGEO Interdepartmental Research Center of Research of Geomatics
  corresponding: francesco.pirotti@unipd.it
  email: francesco.pirotti@unipd.it
  footnote: 1
  name: Francesco Pirotti
  orcid: 0000-0002-4796-6406
- affiliation: TESAF Department
  email: francesco.pirotti@unipd.it
  footnote: 2
  name: Francesco Pirotti
  orcid: 0000-0002-4796-6406
date: "`r Sys.Date()`"
output:
  pdf_document: rticles::elsevier_article
  html_document:
    df_print: paged
    self_contained: false
  word_document: default
csl: elsevier-vancouver.csl
address:
- address: Agripolis, University of Padova, Legnaro 35020, Italy
  code: CIRGEO Interdepartmental Research Center of Research of Geomatics
- address: University of Padova, Legnaro 35020, Italy
  code: TESAF Department
footnote:
- code: 1
  text: Corresponding Author
- code: 2
  text: Equal contribution
journal: Science of Remote Sensing
bibliography: mybibfile.bib
link-citations: yes
abstract: |
  This is the abstract.
  It consists of two paragraphs.
---

_Text based on elsarticle sample manuscript, see [http://www.elsevier.com/author-schemas/latex-instructions#elsarticle](http://www.elsevier.com/author-schemas/latex-instructions#elsarticle)_


Introduction
===================

In this work we present results from the analysis of time-series of RADAR backscatter values over forests that were subject to heavy damage due to extreme wind (VAIA storm - 28 October 2018). The hypothesis is that, with due processing, RADAR backscatter can be used to detect and assess damage of forest, under certain conditions. 

Remote sensing for determining changes in the Earth surface is a common application. Optical remote sensing if very much used, through classification of imagery before and after events and successive comparison, or also by difference of specific band transformations. It is well known that the main drawback of optical imagery is weather and atmospheric condition in general. This is not a problem if the damaged area can be assessed without urgency, ie. waiting for a cloud-free imagery or at least partially cloud-free areas is not a problem. If a more timely assessment must be undertaken, then doing without the atmospheric problem can become a big advantage. This is were active remote sensing with micro-wave wavelength can bring a significant advantage.

The effect of clouds over  RADAR backscatter is negligible, but many other factors concur to backscatter values and variations thereof . 

<p style='text-align: justify;'>  
Satellite open data allows a large audience of researchers to test methods for interpreting phenomena impacting the Earth surface. Optical and SAR data have complementary characteristics that can be integrated to provide more information to models and methods. 
The Sentinel 1 C-band SAR data  [@Torres2012]  and the Sentinel 2 optical multispectral data  [@Drusch2012] provide open data in the two realms of SAR and optical. The datasets are also available as products in Google Earth Engine (GEE), an integrated platform designed to empower not only traditional remote sensing scientists but also a wider audience [@Gorelick2017]. With the availability of both optical and SAR data free of cost and already preprocessed, the Copernicus datasets represent an optimal and rapid tool for the assessment of forest damages, such as windthrows (@VaglioLaurin - not yet published). 
</p>

Early applications of remote sensing in forestry to detect and assess damages dates to the 80's and was related to land-use/land-cover classification using Thematic Mapper (TM),  Landsat Multispectral Scanner (MSS), the Advanced Very High Resolution Radiometer (AVHRR), and the French Systeme Probatoire d'Observation de la Terre (SPOT) are passive sensors applied to classification tasks [@Iverson1989].

Radar data started being used over forest environment to detect deforestation, showing that stronger backscatter signals arrive at the radar sensor from smooth, deforested areas [@Saatchi1997; @Stone1988]. It must be noted that this requires the forest to be free from fallen trunks, which is not true in the case windthrow were stems are left on the ground. 

Investigation on how forest parameters can be estimated with radar also started in the 80's.  A sensor with L-Band radar recording four polarizations (VV, VH, HH, HV) and derived indices from their median values can be used to estimate basal area, tree height, and total tree biomass respectively with a correlation coefficient (r) of 0.50 0.82 and 0.77 [@Sader1987]. 

[@VaglioLaurin2016] arrived to assess biomass with radar and grey level Grey Level Co-occurrence Measure (GLCM) texture features of NDVI reaching  r=0.81.

With respect to windthrow, [@Ruetschi2019] [@Farr_Rosen2007]
 
Material and methods
===================


For both Sentinel 1 and PALSAR/PALSAR-2, 

 
Theory/calculation
===================

## Sentinel 1

Google Earth Engine (GEE) provides Sentinel 1 in preprocessed GRD products with \( \sigma^0 \) (sigma-naught) of VV and VH polarizations, after processing for removing thermal noise, calibrating radiometry and converting \( \beta^0 \) beta-naught to sigma-naught using a digital elevation model (DEM). The DEM at the latitudes of the analysed study areas used is from the  Shuttle Radar Topography Mission (SRTM) that took place in february 2000 @Farr&Rosen2007. Sigma-naught is provided in dB by transformation the backscatter value  \( Y=10*log_{10}(X) \) . @Small2011.  The GEE product was further transformed to provide gamma-naught (\( \gamma^0 \)) values, thus correcting for the local incidence angle with the SRTM product. This removed the bias between ascending and descenging orbits that was evident from plotting the data.

Incidence angle was further corrected using a frequency-histogram based mehod as described in [@Mladenova2013]. This method is not site-specific or sensor-dependant. Is has also proven to be effective not only for small incidence angles, which is the case here as the area is over mountainous region.


 
## PALSAR-2


Polarization data are stored in GEE as 16-bit digital numbers (DN). As per indication in the GEE website, the DN values can be converted to gamma naught (\( \gamma^0 \))  values in decibel unit (dB) using the following equation: 

\[
\begin{aligned}
 \gamma^0 = 10*log_{10}(DN) - 83.0  
\end{aligned}
\]  

where  \( 83.0 \  dB \) offset and \( \gamma^0 \) is in dB. 

values, thus correcting for the local incidence angle with the SRTM product.  

 
Results
===================



 
Discussion
===================


 
 
Conclusions
===================


 

Acknowledgements
===================


This effort is also part of the [VAIA FRONT project - FRom lessong learned to future Options ](https://www.tesaf.unipd.it/ricerca/progetti-dip-tesaf) . 
     
 
Bibliography styles
===================

There are various bibliography styles available. You can select the
style of your choice in the preamble of this document. These styles are
Elsevier styles based on standard styles like Harvard and Vancouver.
Please use BibTeX to generate your bibliography and include DOIs
whenever available.

Here are two sample references: @Feynman1963118 [@Dirac1953888].

References {#references .unnumbered}
==========
